import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 })
const page = await ctx.newPage()
await page.goto('http://localhost:3000/', { waitUntil: 'domcontentloaded', timeout: 60000 })
await page.addStyleTag({ content: 'nextjs-portal{display:none!important}' }).catch(() => {})
await page.waitForTimeout(2000)
await page.screenshot({ path: 'screenshots/00-accueil.png', fullPage: true })
console.log('✓ 00-accueil')
await browser.close()
